from . import start
from . import get_token
from . import delete_all
from . import add_name
from . import new_project
from . import item
from . import off_project
from . import on_project
from . import delete_project
from . import add_rate
from . import admin_panel
